name: Deploy Fitness Tracker MVP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        uses: vercel/vercel-action@v2
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org: ${{ secrets.VERCEL_ORG }}
          project: fitness-tracker-frontend
          prod: true